#!/bin/bash

# Copyright 2011 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file wraps ld and ld.gold.

exec "$(readlink -f "${0}").real" "$@"
